services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=Phuc0312
      - POSTGRES_DB=postgres
    restart: "no"
    volumes:
      - ./postgresql:/var/lib/postgresql/data


  odoo:
    image: odoo:17
    user: root
    depends_on:
      - db
    ports:
      - "31204:8069"
      - "31205:8072"
    tty: true
    entrypoint: ["/entrypoint.sh"]
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=Phuc0312
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./etc/odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
      - //e/odoo/Odoo17/DineFlow:/DineFlow
    restart: "no"

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "31206:8080"
      - "31207:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
      - //e/odoo/Odoo17/DineFlow:/DineFlow
    restart: "no"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "31208:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:31208
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Phuc0312
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - odoo
    restart: "no"

volumes:
  jenkins_home:
  n8n_data:
  odoo_data:
