[options]
addons_path = /mnt/extra-addons
server_wide_modules = base,web
data_dir = /var/lib/odoo

admin_passwd = dineflow_master_2024

db_host = db
db_port = 5432
db_user = odoo
db_password = Phuc0312
db_name = intern
db_maxconn = 64

log_level = info

workers = 0
max_cron_threads = 2
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
limit_time_cpu = 60
limit_time_real = 120
limit_time_real_cron = 0
limit_request = 8192